In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [3]:
import time

In [11]:
a = np.random.rand(100000)
b = np.random.rand(100000)
tic = time.time()
c = np.dot(a,b)
toc = time.time()
print('Vectorized version:'+str(1000*(toc-tic))+'ms')

c = 0
tic = time.time()
for i in range(100000):
    c += a[i]*b[i]
toc = time.time()
print(c)
print('For loop:'+str(1000*(toc-tic))+'ms')

Vectorized version:0.9980201721191406ms
25013.96557728302
For loop:164.55769538879395ms


In [12]:
a = np.array([
    [56,0,4.4,68],
    [1.2,104,52,8],
    [1.8,135,99,0.9]
])
a

array([[ 56. ,   0. ,   4.4,  68. ],
       [  1.2, 104. ,  52. ,   8. ],
       [  1.8, 135. ,  99. ,   0.9]])

In [15]:
cal = a.sum(axis=0)
cal

array([ 59. , 239. , 155.4,  76.9])

In [17]:
percentage = 100*a/cal
percentage

array([[94.91525424,  0.        ,  2.83140283, 88.42652796],
       [ 2.03389831, 43.51464435, 33.46203346, 10.40312094],
       [ 3.05084746, 56.48535565, 63.70656371,  1.17035111]])